name: Python AI Chatbot CI/CD with Debug
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint with flake8
        run: |
          # Only lint the api.py file, ignore app.py with Streamlit references
          flake8 api.py --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings
          flake8 api.py --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Debug Network
        run: |
          echo "GitHub Actions IP information:"
          curl -s ifconfig.me
          echo ""
          echo "Checking connectivity to EC2 host:"
          nc -zv ${{ secrets.EC2_HOST }} 22 -w 5 || echo "Connection failed"

      - name: Create SSH directory
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.EC2_SSH_KEY }}
          known_hosts: unnecessary
          if_key_exists: replace

      - name: Debug SSH Key
        run: |
          ls -la ~/.ssh/
          echo "SSH Key Fingerprint:"
          ssh-keygen -l -f ~/.ssh/id_rsa || echo "Failed to get fingerprint"

      - name: SSH with Verbose Output
        run: |
          ssh -v -o BatchMode=yes -o ConnectTimeout=10 -o StrictHostKeyChecking=no ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} echo "SSH connection test"
